version: 2.1
orbs:
  node: circleci/node@4.1.0
  slack: circleci/slack@4.4.2
  browser-tools: circleci/browser-tools@1.1.0
jobs:
  test:
    docker:
      - image: cimg/node:lts-browsers
    steps:
      - checkout
      - browser-tools/install-browser-tools
      - node/install-npm
      - run:
          command: npm run test:configurationFile
      - run:
          command: npm run test:backend
      - store_test_results:
          path: Reports
      - slack/notify:
          event: fail
          template: basic_fail_1
workflows:
  e2e-test:
    jobs:
      - test
